### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by eschricker** [enriconale/cognito-authenticator#1]
Could you please provide information under which license the code is distributed?

It would be nice if you could tell if the code could be used in a commercial product.

**Comment by enriconale** [comment]
Hi @eschricker 

I've added the LICENSE file. You can use the code everywhere you need it (I hope it's still working, it's been months since the last edit) :smiley:

**Comment by eschricker** [comment]
Thanks alot :) 
I haven't found another source which implements the SRP for cognito and the code is still working fine.
